services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Different port to avoid conflicts
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-service
      - auth-service

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  app-service:
    build:
      context: .
      dockerfile: app-service/Dockerfile
    image: idleness76/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP}
      AUTH_SERVICE_HOST_NAME: auth-service
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: idleness76/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET}