services:
  app-service:
    build:
      context: . # Build from root directory (workspace root)
      dockerfile: app-service/Dockerfile
    image: idleness76/app-service
    restart: "always"
    environment: # set up environment variables
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use localhost as the default value
      AUTH_SERVICE_HOST_NAME: auth-service
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    build:
      context: . # Build from root directory (workspace root)
      dockerfile: auth-service/Dockerfile
    image: idleness76/auth-service
    restart: "always"
    ports:
      - "3000:3000"