services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-service
      - auth-service

  app-service:
    build:
      context: .
      dockerfile: app-service/Dockerfile
    image: idleness76/app-service
    restart: "always"
    environment:
      - AUTH_SERVICE_HOST_NAME=auth-service
      - AUTH_SERVICE_IP=auth-service
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: idleness76/auth-service
    restart: "always"