services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Different port to avoid conflicts
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-service
      - auth-service
    restart: "always"

  app-service:
    build:
      context: .
      dockerfile: app-service/Dockerfile
    image: idleness76/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP}
      AUTH_SERVICE_HOST_NAME: auth-service
    depends_on:
      auth-service:
        condition: service_started
  
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: idleness76/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    depends_on:
      db

  db:
    image: postgres:alpine
    restart: "always"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local